model_name: ar_baseline

backbone_with_air_tokens: True # model sees air tokens for all x_t input 

global_structure_cond: False # True 

# from medium.yaml / small.yaml / tiny.yaml  
hidden_size: 768 #1024 / 768 / 512 
cond_dim: 128 # 128 / 128 / 128
length: 1024 # 1024 / 1024 / 1024 
n_blocks: 12 # 24 / 12 / 8 
n_heads: 12 # 16 / 12 / 8 
scale_by_sigma: True
dropout: 0.1
tie_word_embeddings: False

learned_pos_embeddings: False # False / True 