model_name: latent_diffusion

noise_steps: 1000  # T
ema: true  # exponential moving average
ema_decay: 0.99  # exponential moving average decay rate
lambda_variational: 0.0001
vlb: false 
init_step_vlb: 1000

input_channels: 16  #NOTE: should be same as sparse_vae.yaml latent_channels

scheduler:
  beta_start: 0.0001 #0.000025
  beta_end: 0.02 #0.005
  T: 1000 #4000 # NOTE: ensure this is the same as T above


backbone:
  resolution: 16 #16
  in_channels: ${..input_channels}
  out_channels: ${..input_channels}
  model_channels: 768
  cond_channels: None
  num_blocks: 12
  num_heads: 12
  mlp_ratio: 4
  patch_size: 1 # 2
  pe_mode: ape
  qk_rms_norm: true
  use_fp16: false  

