checkpoint_monitor:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint  # Change this!
  monitor: val/loss
  mode: min
  save_top_k: 1
  save_last: True
  dirpath: ${checkpointing.checkpoint_dir}/checkpoints
  filename: ${model_name}_best
  auto_insert_metric_name: False
  verbose: True

