# This is adapted from the default config in https://github.com/kuleshov-group/mdlm/blob/master/configs/config.yaml

defaults:
  - _self_
  - /callbacks: [checkpoint_every_n_steps, checkpoint_monitor] #[checkpoint_every_n_steps, checkpoint_monitor, learning_rate_monitor]
  - /data: minecraft
  - /model: scaffold_diffusion #scaffold_diffusion / small / ar_baseline / vqvae_baseline / latent_flow / latent_diffusion / sparse_vae / 
  - /strategy: ddp
  - /noise: loglinear
  - /lr_scheduler: cosine_decay_warmup #constant_warmup

mode: train  # train / sample_eval / autoencode 
diffusion: absorbing_state
backbone: dit  # unet / dit_3d / dit 
parameterization: subs  # subs / d3pm / sedd
time_conditioning: False
T: 0  # 0 (continuous time) / 1000 
subs_masking: False
mask_token_id: null 
overfit: False 

# naming
model_name: scaffold_diffusion #scaffold_diffusion / small / ar_baseline / vqvae_baseline / latent_flow / latent_diffusion / sparse_vae / 

seed: 1

latent:
  vae_ckpt: /home/jsjung00/Desktop/Code/voxeldiffusion/outputs/minecraft/2025.07.24/111538/checkpoints/39-50000.ckpt #Add your own ckpt path
  diffusion_ckpt: /home/jsjung00/Desktop/Code/voxeldiffusion/outputs/minecraft/2025.07.24/091224/checkpoints/scaffold_best.ckpt #Add your own ckpt path

multinomial_vqvae:
  vqvae_ckpt: /home/jsjung00/Desktop/Code/voxeldiffusion/outputs/minecraft/2025.08.22/223833/checkpoints/vqvae_best.ckpt #Add your own ckpt path
  diffusion_ckpt: /home/jsjung00/Desktop/Code/voxeldiffusion/outputs/minecraft/2025.08.22/234253/checkpoints/latent_multinomial_best.ckpt #Add your own ckpt path

loader:
  global_batch_size: 28 
  eval_global_batch_size: 28
  # Note: batch_size and eval_batch_size are **per machine**
  batch_size: 28
  eval_batch_size: 28
  num_workers: 12
  pin_memory: True

sampling:
  predictor: ddpm_cache  # analytic / ddpm / ddpm_cache
  steps: 1024
  noise_removal: True
  num_sample_batches: 2 #1 / 90  # Total samples: `num_gpus` * `loader.eval_batch_size` * num_sample_batches
  num_sample_log: 2
  semi_ar: False
  stride_length: 1
  num_strides: 1
  val_sample_freq: 1000 # 10

training:
  ema: 0.9999 
  use_ema: True 
  antithetic_sampling: True
  importance_sampling: False
  sampling_eps: 1e-3
  change_of_variables: False

eval:
  checkpoint_path: /home/jsjung00/Desktop/Code/voxeldiffusion/outputs/minecraft/2025.07.13/072426/checkpoints/69-25000.ckpt #Add your own ckpt path
  disable_ema: False
  compute_generative_perplexity: False
  perplexity_batch_size: 8
  compute_perplexity_on_sanity: False
  gen_ppl_eval_model_name_or_path: gpt2-large  # gpt2-large, meta-llama/Llama-2-7b-hf
  generate_samples: True

optim:
  weight_decay: 0
  lr: 0.00005 # 3e-4 / 1e-5 / 1e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8

trainer:
  _target_: lightning.Trainer
  accelerator: cuda
  num_nodes: 1
  devices: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5 #1.0 / 0.5
  precision: '32-true' # bf16-mixed / 32-true 
  num_sanity_val_steps: 2
  max_steps: 100_000 #100_000 
  log_every_n_steps: 10
  #limit_train_batches: 1.0   # train on full dataset, can be used to toggle quick run
  #limit_val_batches: 1.0     # validate on full dataset, can be used to toggle quick run
  check_val_every_n_epoch: 1 #5
  enable_progress_bar : True

wandb:
  project: voxel-diffusion
  notes: Training latent flow with b=0.001 vae 
  group: null
  job_type: null
  name: ${now:%Y.%m.%d}-${now:%H%M%S} 
  id: ${.name}_${seed}
  tags:
    - ${noise.type}
    - ${data.train}
    - ${data.valid}

hydra:
  run:
    dir: ./outputs/${data.train}/${now:%Y.%m.%d}/${now:%H%M%S}
  job:
    chdir: true

checkpointing:
  # Use custom `save_dir` if, e.g., saving to S3 bucket, otherwise leave this parameter as is
  checkpoint_dir: ${cwd:}
  save_dir: ${cwd:}
  # Note: `checkpoints` path should correspond to `checkpoint_every_n_steps.dirpath`
  resume_from_ckpt: false #true
  resume_ckpt_path: /home/jsjung00/Desktop/Code/voxeldiffusion/outputs/minecraft/2025.07.29/100731/checkpoints/scaffold_best.ckpt #Add your own ckpt path
